services:
  db:
    image: postgres:16-alpine
    container_name: edgebook-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-edgebook}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: edgebook-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ../../
      dockerfile: infra/docker/api.Dockerfile
    container_name: edgebook-api
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-edgebook}?schema=public
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ../../
      dockerfile: infra/docker/worker.Dockerfile
    container_name: edgebook-worker
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-edgebook}?schema=public
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis

  web:
    build:
      context: ../../
      dockerfile: infra/docker/web.Dockerfile
    container_name: edgebook-web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:
