// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    // CLI commands (generate/migrate/seed) need a direct, non-pooled connection —
    // Supabase's pgbouncer pooler (used for DATABASE_URL at runtime) doesn't support
    // the prepared statements Prisma's migration engine relies on. Set DIRECT_URL
    // when pointing this at Supabase; falls back to DATABASE_URL for local dev.
    url: process.env.DIRECT_URL ?? process.env.DATABASE_URL,
  },
});
